name = "Cielpack 1.20.1"
author = "Robtic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0500ceb0a87f1ed035a012971602d8f8707331dc3a62d0e3c6fc0018b286463d"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
